[phases.setup]
nixPkgs = [
  "poppler_utils",     # PDF processing
  "tesseract",         # OCR
  "zbar",              # QR/barcode
  "opencv4",           # OpenCV
  "libglvnd",          # libGL.so.1 (for OpenCV headless)
  "python310Full"      # Full Python
]

# Optional: Avoid apt conflicts — remove aptPkgs unless truly needed.


[phases.setup]
  aptPkgs = ["libgl1-mesa-glx","libgl1"]
